# Generated by Django 2.1.5 on 2019-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('code', models.TextField(blank=True)),
                ('options', models.TextField(blank=True)),
                ('solution', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('category', models.CharField(max_length=200)),
                ('questionImage', models.CharField(blank=True, max_length=300)),
                ('hintImage', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=None, related_name='questions', to='app.Challenge')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
