# Generated by Django 2.1.5 on 2019-02-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_challengecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.TextField(default='slug_name'),
            preserve_default=False,
        ),
    ]
